
name: AStyle Checker

on:
  push:
    branches: [ master, develop ]
    paths: 
      - '**.cs'
      - '**.h'
      - '**.cpp'
      - '**.c'
  pull_request:
    branches: [ master, develop ]
    paths: 
      - '**.cs'
      - '**.h'
      - '**.cpp'
      - '**.c'

jobs: 
  astyle-code:
   name: astyle check
   runs-on: self-hosted
   
   steps:
    - uses: actions/checkout@v1
      env: 
        DEFAULT_BRANCH: develop
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        fetch-depth: 1

    - name: install dependencies
      run: sudo apt-get install astyle
      
    - name: astyle check
      run: make astyle-check

    - name: Display Corrections
      if: failure()
      run: |
        make astyle
        git diff
